### ISSUE TITLE
exportDatatables  not working with jdk23 and gradle 8.10 as observed

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite-spring#618]
<img width="758" alt="{15ABE437-B1E4-41C4-8B32-F5C28A31B5DA}" src="https://github.com/user-attachments/assets/65b2a253-2387-4888-bbd7-bc8ee0eefadd">

Script compilation error:

  Line 65:     exportDatatables = true
               ^ Cannot access 'exportDatatables': it is private in 'RewriteExtension'

1 error

**Comment by nagkumar** [comment]
followed the instructions as at https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_2

**Comment by timtebeek** [comment]
Hi both; thanks for the report! I've tried to replicate this with [the spring-projects/spring-petclinic build.grade](https://github.com/spring-projects/spring-petclinic/blob/main/build.gradle), but when I add the following I see no such issues:
```diff
diff --git a/build.gradle b/build.gradle
index a5175df..0f44c44 100644
--- a/build.gradle
+++ b/build.gradle
@@ -6,6 +6,8 @@ plugins {
   id 'org.cyclonedx.bom' version '1.10.0'
   id 'io.spring.javaformat' version '0.0.43'
   id "io.spring.nohttp" version "0.0.11"
+
+  id("org.openrewrite.rewrite") version("6.26.0")
 }
 
 apply plugin: 'java'
@@ -53,6 +55,13 @@ dependencies {
   testImplementation 'org.testcontainers:mysql'
   checkstyle "io.spring.javaformat:spring-javaformat-checkstyle:${springJavaformatCheckstyleVersion}"
   checkstyle "com.puppycrawl.tools:checkstyle:${checkstyleVersion}"
+
+  rewrite("org.openrewrite.recipe:rewrite-spring:5.22.0")
+}
+
+rewrite {
+  activeRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2")
+  exportDatatables = true
 }
```

Do note that this is with `build.gradle`, not `build.gradle.kts`. You might need to call a function to set that value, although I'm not sure there. But even then, you would only see changes in files other than your build scripts, pending:
 - https://github.com/openrewrite/rewrite/issues/3291

**Comment by timtebeek** [comment]
I've given it a quick try and indeed `exportDatatables(true)` seems to work for `.kts` files, but again: do not expect to see your dependencies updated yet. For that look towards the issue linked above.

- Here's a PR to update the docs: https://github.com/openrewrite/rewrite-recipe-markdown-generator/pull/141
